services:
  - type: web
    name: zerodha-clone-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DASHBOARD_URL
        sync: false
